#!/bin/bash
# Start a local validator inside WSL with the duel program preloaded and the Pyth
# fixture accounts (tests/fixtures/accounts/*.json, generated by `pnpm fixtures` on
# Windows) injected, then fund the test wallet.
#
# Usage (from Windows):  wsl -d Ubuntu -- bash -lc 'bash /mnt/c/.../programs/duel/wsl/validator.sh'
# Stop with:             wsl -d Ubuntu -- bash -lc 'pkill -f solana-test-validator'
set -euo pipefail

SRC="${DUEL_SRC:-$(cd "$(dirname "$0")/.." && pwd)}"
PROGRAM_ID="AN2TEyFH3zCsv5MENn2uo9LJx69J2EUC8iScAVeDbW25"
SO="${DUEL_SO:-$HOME/duel/target/deploy/duel.so}"
[ -f "$SO" ] || SO="$SRC/target/deploy/duel.so"
LEDGER="${DUEL_LEDGER:-$HOME/duel-ledger}"
LOG="${DUEL_VALIDATOR_LOG:-$HOME/duel-validator.log}"
WALLET="${ANCHOR_WALLET:-$HOME/.config/solana/id.json}"

ARGS=(-r --quiet --ledger "$LEDGER" --bpf-program "$PROGRAM_ID" "$SO")
shopt -s nullglob
for f in "$SRC"/tests/fixtures/accounts/*.json; do
  pk=$(jq -r .pubkey "$f")
  ARGS+=(--account "$pk" "$f")
  echo "fixture: $pk <- $(basename "$f")"
done

pkill -f solana-test-validator >/dev/null 2>&1 || true
sleep 1
setsid nohup solana-test-validator "${ARGS[@]}" >"$LOG" 2>&1 &
echo "validator starting (pid $!), log: $LOG"

for _ in $(seq 1 90); do
  if solana cluster-version -u localhost >/dev/null 2>&1; then break; fi
  sleep 1
done
solana cluster-version -u localhost
solana airdrop 100 "$(solana-keygen pubkey "$WALLET")" -u localhost
